# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under cvt_mlops_stacks_demo/resources/*
# and cvt_mlops_stacks_demo/databricks.yml with prod deployment target configs,
# when PRs are merged into the release branch
name: Bundle Deployment for cvt_mlops_stacks_demo Prod

on:
  push:
    branches:
      - 'release'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./cvt_mlops_stacks_demo

env:
  #ARM_TENANT_ID: ${{ secrets.PROD_AZURE_SP_TENANT_ID }}
  #ARM_CLIENT_ID: ${{ secrets.PROD_AZURE_SP_APPLICATION_ID }}
  #ARM_CLIENT_SECRET: ${{ secrets.PROD_AZURE_SP_CLIENT_SECRET }}
  DATABRICKS_HOST: https://adb-8590162618558854.14.azuredatabricks.net
  DATABRICKS_TOKEN : ${{ secrets.DB_TOKEN }}


jobs:
  prod:
    concurrency: cvt_mlops_stacks_demo-prod-bundle-job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: Validate Bundle For Prod
        id: validate
        run: |
          databricks bundle validate -t prod
      - name: Deploy Bundle to Prod
        id: deploy
        run: |
          databricks bundle deploy -t prod
      - name: Run Feature Engineering Workflow for Test Deployment Target in Staging Workspace
        id: feature_engineering
        run: |
          databricks bundle run write_feature_table_job -t prod
      - name: Run Training Workflow for Test Deployment Target in Staging Workspace
        id: training
        run: |
          databricks bundle run model_training_job -t prod
